### ISSUE TITLE
Super cool. Will it add privacy feature?

### ISSUE THREAD

**Issue by LuozhuZhang** [kleros/kleros-v2#418]
Nice to meet u!

Your project is very cool, I think the **proof of humanity** is the beginning of democratic application on the chain, and the beginning of blockchain becoming mainstream.

I use the v1 contract, and I found a significant problem, the videos uploaded by users are transparent (e.g. I can sew vitalik's [verification video](https://www.youtube.com/shorts/WH83_Fad7E4)), is it possible to support privacy features? Given the maturity of zkp technology, what are your concerns?

Thank you so much for your ideas, looking forward to seeing more progress! willing to communicate at any time!~

**Comment by jaybuidl** [comment]
Hey Luozhu, thanks for the feedback! 

The video cannot be made private because it would prevent the decentralized curation of the PoH registry by the community, which looks for sybils. The trade-off is that a video is less intrusive than biometrics for example, and PoH does not require any real name, but indeed it does leak the photo, video and audio of the applicants. 

I could see ZK being used as an extra layer on top of the current PoH registry and let the other apps integrate with that privacy layer instead of PoH directly. That would be really cool!

Also Sismo has launched a ZK badge for PoH: https://app.sismo.io/proof-of-humanity
